travis:
  secure:
    BINSTAR_TOKEN: VphyDvqQKavW5PnuETSD63FqkWp0DBgNHQAsavarYi5ZZZOz4WVSTfifDQHgXcb2/uB2FesMiQ0zbkmodaDBRRbB17lHO3TCqszvGEXWOh2wW1iGkrLK73p/wXq/1di61BtiwOoIPy0G70E9/YIOfC20UlEPe2tzW8irSy5GxFauhfhedIyrHhLN72yMu7KAcOyRexXSntc6h0Zjx17F1lBipSF1ffvwqec3boKkYx4wOruTggf65m2SXEe8p3DCkBlEWYmMRs0X014miqSY1TMd+qj4Dqd4HbO1Y4vqgWdBkwry9yDC8UPkDOPSeKdmLeXUjKn978oEPTbwhvRb3uwapRjkdb78M6XDo302w+XZXxW42AZ0DmGuJKfWjag5vVHeSy5gdFYD4aZs/4tNdeERMzRS/zjxsJyPs/HMSkxaB4ms3f+zRxehcp3FFEPKix42L2FPgQrQ7pcbyUl73KnK8XZJZMwlA/xolsaIhrFnuKLe76kGTXOY4lBD39PhVLvN2g+l0cugG7iJnDZT7KpFbEhb2bYRE4w/EuZ8uaJmlvKaf6qNO8OALLlb8XrEFN50xUGk54gDK8rakehR1cpcwbT9SkCwg3cA8iQJQhl6aaWl9YGLbkuliK4jpfZaYiuoArElGWm4hm83ysLkhakYcDBq/714kLS0i5CV+nQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
