travis:
  secure:
    BINSTAR_TOKEN: fWW6BVqL9Jr5CAd/WLXahJ433thPm1h+LLwZaeV8M5xl5Jr4RthKNZn3wNud9CrcbuRkqnpXl4CffqvXsKYX+cMY9SmrOdfXYk0AAgRCLybzdw2at8qhHrztRB05JS2qA9O82LOu/lPTNByCjYWauogLWiVTfE6kqZIqGtB0sce64g1nwduYfn4O2D5quZjOVdaqD+s5ij817qVmCOXsUXiFQ8xj7tMYZmyknvvchHy0uIbxql4yD9t0yYhufvoQAoJiJLD/RuEUk3mD828qB1UMCB7QjnkcI8Iy5GAcgVSMUG+R6vh2ou5Da4F+ltwTFRwQtusxdO2xfw47pSp4gMmGL6MI6RPnIYWWKsnLWuk31nPzTNrZdhnfWtIkLbWL30PdEkdpKwVbjeFMSO9e+BnC93drIj7k4c/YLyGThyAaw+mIv2crRRnGo4yo04y2bBQXL3v8ClxL8GFA+kKzeGE1aKLejA39oOsVVt4NVWIOR0eyXmQGIuaTa562wWHR8mPUE4s8A2kxcf68FlaQ1t54iP2HIhHGm/mzpfzQuGaaLE6xkWBr8M+Xhd1Ae2tLCF9WzDY3WOyawXMqSUpQjhHYtoNLlELl4z91u1hqSLjv75sHBXmLMbEYrte6+KbRox24WmwVaqGai3gUDsC+HrQ4DODZKJadCRBbaV4BDaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
